apiVersion: v1
kind: Service
metadata:
  name: axonserver-gui
  labels:
    app: axonserver
spec:
  selector:
    app: axonserver
  ports:
  - name: gui
    port: 8024
    targetPort: 8024
  type: LoadBalancer
  sessionAffinity: ClientIP
---
apiVersion: v1
kind: Service
metadata:
  name: axonserver
  labels:
    app: axonserver
spec:
  selector:
    app: axonserver
  ports:
  - name: grpc
    port: 8124
    targetPort: 8124
  clusterIP: None
