{{- if eq .Values.properties.kind "InlineSecret"  -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.properties.secretName | default "axon-server-secret" }}
  labels:
    {{- include "axon-server-se.labels" . | nindent 4 }}
stringData:
  axonserver.properties: |
{{ .Values.properties.content | indent 4 -}}
{{- end -}}